CREATE SCHEMA IF NOT EXISTS PUBLIC AUTHORIZATION sa;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS LOGS;

CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    birthday DATE,
    login_ID INTEGER NOT NULL UNIQUE,
    city VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PUBLIC.ROLE (
    name ENUM('Administration', 'Clients', 'Billing'),
    description VARCHAR(255),
    id INTEGER NOT NULL REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USER_ROLE (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   user_id INTEGER REFERENCES USERS(id),
   role_id INTEGER REFERENCES ROLE (id)
);

CREATE TABLE IF NOT EXISTS LOGS (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    date DATE,
    log_level VARCHAR(5),
    message VARCHAR(255)
);

